apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: martina-system
  description: A test system
spec:
  type: service
  owner: user/martina
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: martina-system-2
  description: A test system
spec:
  owner: user/martina
